### PR TITLE
Patchwork

### LINKED ISSUE #1: Provide conditional method check before run single patch
#### Example syntax
```php
use Dentro\Patcher\Patch;

return new class extends Patch
{
    /**
     * Run patch script.
     *
     * @return void
     */
    public function patch(): void
    {
        //
    }
    
    public function eligible(): boolean
    {
        return false;
    }
};

```

If `eligible()` method return false. the `patch` method will not be called. The output of console will seems like 
```shell
Patching: 2020_10_09_124616_add_attachment_beep
Skipped: 2020_10_09_124616_add_attachment_beep is not eligible to run in current condition
```

#### The reason why we need this : 
Patches are often created because of some condition on certain environment, E.g. The staging environment database was broken due to some mistake by developer. But, other developer environments and production are not effected with the bug. So we only need to run this patch on staging environment and in other environments we still can run `artisan patcher:run` without worry about the error `Model with id blablabla not found...` that written in `patch` method.

### PR DESCRIPTION
**Pull request by veelasky**
- [x] add `eligible()` method to check whether the patch should run, closes #1 
- [x] disable patch run within transaction, because it is different behavior than migration, patch should not be enclosed within transaction, let the developer decide, this package usually handle a lot of data  and some can be lost in huge amount of transactions.

### CODE REVIEW

File: src/Patcher.php [hunk 1]
```diff
@@ -71,6 +75,21 @@ protected function patch(string $file, int $batch, bool $pretend): void
...
+     */
+    public function isEligible(Migration $migration): bool
+    {
+        if (method_exists($migration, 'eligible')) {
+            return $migration->eligible();
+        }
+
+        return true;
+    }
+
```
Comment (muhajirinlpu) [inline src/Patcher.php]: what is the use case of this method ?

Comment (veelasky) [reply src/Patcher.php]: the one that u requested #1 🤦

Comment (muhajirinlpu) [reply src/Patcher.php]: is this method supposed to called on line 66 ?
image
